//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.donhang = new HashSet<donhang>();
        }
    
        public string sdtkh { get; set; }
        public string matkhau { get; set; }
        public string hovaten { get; set; }
        public string email { get; set; }
        public string gioitinh { get; set; }
        public string ngaysinh { get; set; }
        public string diachi { get; set; }
        public string anhkh { get; set; }
        public string diadiemyeuthich { get; set; }
        public string diadiemkem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donhang> donhang { get; set; }
    }
}
