//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class diadiemanuongEntities : DbContext
    {
        public diadiemanuongEntities()
            : base("name=diadiemanuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<chitietdonhang> chitietdonhang { get; set; }
        public virtual DbSet<danhmuc> danhmuc { get; set; }
        public virtual DbSet<donhang> donhang { get; set; }
        public virtual DbSet<khachhang> khachhang { get; set; }
        public virtual DbSet<loaiquanan> loaiquanan { get; set; }
        public virtual DbSet<quan> quan { get; set; }
        public virtual DbSet<thucan> thucan { get; set; }
    }
}
