//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thucan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thucan()
        {
            this.chitietdonhang = new HashSet<chitietdonhang>();
        }
    
        public string idta { get; set; }
        public string tenta { get; set; }
        public string anhta { get; set; }
        public string thongtinveta { get; set; }
        public string takhuyenmai { get; set; }
        public string tahot { get; set; }
        public string trangthai { get; set; }
        public string giabandau { get; set; }
        public string giahientai { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ngaydang { get; set; }
        public Nullable<int> giamgia { get; set; }
        public Nullable<int> luotxem { get; set; }
        public Nullable<int> idquan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdonhang> chitietdonhang { get; set; }
        public virtual quan quan { get; set; }
    }
}
